layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    - dotfiles
    - Ras96
    - Ras96.github.io

social_media:
  twitter: ras0q
  website: https://ras96.github.io

topics:
  - name: Backend
    website_url: https://github.com/topics/backend
    image_url: https://image.flaticon.com/icons/png/512/2166/2166820.png
  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/main/topics/go/go.png
  - name: Rust
    web_url: https://github.com/topics/rust
    image_url: https://raw.githubusercontent.com/github/explore/main/topics/rust/rust.png
  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/main/topics/typescript/typescript.png
  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/github/explore/main/topics/cpp/cpp.png
  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/main/topics/docker/docker.png
  - name: Deep learning
    web_url: https://github.com/topics/deep-learning
    image_url: https://image.flaticon.com/icons/png/512/2103/2103620.png
